name: json2builtvalue
description: An absolute bare-bones web app.
version: 2.0.0
#homepage: https://www.example.com
#author: rafal.wachol <email@example.com>

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  test: "^1.0.0"
  code_builder: "^4.0.0"
  recase: "^4.0.0"
  tuple: "^2.0.0"

dev_dependencies:
  build_runner: ^2.0.0
  build_web_compilers: ^3.0.0
